---
- hosts: localhost
  vars_files:
    - vars/variables.yml
  tasks:
  - name: make sure required packages are installed
    become: yes
    apt:
      name: "{{ packages }}"
      state: latest

  - name: Update and upgrade apt packages
    become: yes
    apt:
      update_cache: yes
      upgrade: dist
      autoclean: yes
      autoremove: yes
      purge: yes
      cache_valid_time: 86400 #One day
