---
- 
  hosts: localhost
  name: 'Update Debian based distro'
  vars_files:
    -
      ../vars/pck_managers_deps.yaml
  tasks:
    # Debian based distros
    - 
      name: [DEBIAN] make sure required packages are installed
      become: yes
      apt:
        name: "{{ packagesApt }}"
        state: latest
      when: ansible_os_family == "Debian"
    - 
      name: [DEBIAN] Update and upgrade apt packages
      become: yes
      apt:
        update_cache: yes
        upgrade: dist
        autoclean: yes
        autoremove: yes
        purge: yes
        cache_valid_time: 86400 #One day
      when: ansible_os_family == "Debian"
    # RedHat based distros
    - 
      name: [RH] make sure required packages are installed
      become: yes
      dnf:
        name: "{{ packagesDnf }}"
        state: latest
      when: ansible_os_family == "RedHat"
    -
      name: [RH] Update packages using dnf
      dnf:
        update_cache: yes
        autoremove: yes
      when: ansible_os_family == "RedHat"
    -
      name: [SUSE] Update packages using yum
      yum:
        update_cache: yes
        autoremove: yes
      when: ansible_os_family == "SUSE"
